version: '3.1'
services:
  jenkins:
    build:
      context: ./master
      dockerfile: ./Dockerfile
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:8080'
      - '50000:50000'
    image: localhost:5000/jenkins
  jenkins-slave:
    build:
      context: ./slave
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - 'JENKINS_URL=http://jenkins:8080'
    image: localhost:5000/jenkins-slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Expose the docker daemon in the container
      - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
    depends_on:
      - jenkins
